#!/bin/bash
#PBS -q batch
#   specify the queue batch, express or bigmem
#PBS -l nodes=1:ppn=12
#   request 1 processor on 1 node
#PBS -l walltime=120:00:00
#   choose a walltime slightly longer than your job will take
#PBS -j oe

cd $PBS_O_WORKDIR

cd /scratch/haohu/Paysonia/05_trinity_bigmem

/scratch/haohu/bin/signalp-4.1/signalp -f short -n Trinity.longest.fasta.transdecoder.pep.signalp.out Trinity.longest.fasta.transdecoder.pep