#!/bin/bash
#PBS -q express
#   specify the queue batch, express or bigmem
#PBS -l nodes=1:ppn=2
#   request 1 processor on 1 node
#PBS -l walltime=1:00:00
#   choose a walltime slightly longer than your job will take
#PBS -j oe

module load perl/5.18.1

cd $PBS_O_WORKDIR

cd /scratch/haohu/Paysonia/07_trinotate

/scratch/haohu/bin/trinotate-3.1.1/Trinotate /scratch/haohu/Paysonia/07_trinotate/Trinotate.0511.plants.sqlite report > trinotate_annotation_report.xls